config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :accounts
  resources :products

  resource :cart, only: :show do
    collection do
      get 'order'
    end
  end
  post '/carts/add_product', to: 'carts#add', as: 'add_to_cart'
  delete '/carts/remove_product', to: 'carts#remove', as: 'remove_from_cart'
  match '/send_mail', to: 'carts#send_mail', via: 'post'

  root 'products#index'

end

app/models/account.rb
class Account < ActiveRecord::Base

  has_one :cart
  has_many :friendships
  has_many :friends, through: :friendships,
                     dependent: :destroy
  belongs_to :user

  validates :name, presence: true, allow_blank: false, format: { with: /(?!^\d+\z)\A.+\z/, message: "can't consists of only digits" }, length: { in: 4..15 }
  validates :age, presence: true, allow_blank: false, inclusion: { in: 18..100, message: 'only from 18 to 100' }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :products
  belongs_to :account
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :account
  belongs_to :friend, class_name: 'Account'

  after_create :create_inverse, unless: :inverse?
  after_destroy :destroy_inverses, if: :inverse?

  def create_inverse
    self.class.create(inverse_friend_options)
  end

  def destroy_inverses
    inverses.destroy_all
  end

  def inverse?
    self.class.exists?(inverse_friend_options)
  end

  def inverses
    self.class.where(inverse_friend_options)
  end

  def inverse_friend_options
    { friend_id: account_id, account_id: friend_id }
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :cart

  has_attached_file :image, styles: { medium: '300x300>', thumb: '60x60>'}, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :price, numericality: {greater_than: 0}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  has_one :account

  ROLES = %i[admin moderator author banned]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(email: data['email'],
                         password: Devise.friendly_token[0, 20])
    end
    user
  end

  def welcome_user_email
    UserMailer.welcome_user_email(self).deliver_later
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  #before_action :authenticate_user!
  #before_action :user_admin?
  #before_action :authorize_admin, except: :new
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.all.order(:age)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    if @account.save
      AccountMailer.welcome_email(@account).deliver_later
      redirect_to accounts_path
      flash[:success] = "Account #{@account.name} created!!!"
    else
      render 'new'
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    if @account.update(account_params)
      flash[:info] = "Account #{@account.name} updated!!!"
      redirect_to accounts_path
    else
      render 'new'
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    flash[:danger] = "Account #{@account.name} deleted!"
    redirect_to accounts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:name, :age)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :set_current_cart
  before_action :set_locale

 private
  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end


  def set_current_cart
    session[:cart_id] ||= Cart.create.id
  end
end

app/controllers/callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :cart_find
  before_action :total_price_of_products

  def show
  end

  def add
    @products_in_cart << Product.find(params[:product_id])
  end

  def order
  end

  def send_mail
    if OrderMailer.order_email(current_user.email)
      redirect_to products_path
      OrderMailer.order_email(current_user.email).deliver_later
      @products_in_cart.clear
      flash[:success] = 'order_created'
    else
      render 'order'
    end
  end

  private

  def cart_find
    @products_in_cart = Cart.includes(:products).find(session[:cart_id]).products || Cart.create(:cart_id => params[:id])
  end

  def total_price_of_products
    @total_sum = cart_find.sum(:price)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action :authenticate_user!, except: [:index]
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    # session[:view_count] += 1
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:create] = I18n.t 'msg_create'
      redirect_to products_path
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @product.destroy
    flash[:destroy] = I18n.t 'msg_destroy'
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:success] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/product_helper.rb
module ProductHelper
  def colored_class(key)
    return 'alert-success' if key.to_sym == :create
    'alert-danger' if key.to_sym == :destroy
  end

  def product_list_partial_name
    @products.empty? ? 'empty' : 'list'
  end
end

app/views/accounts/_form.html.haml
.all_file
= form_for @account, :html => {:class => 'form-horizontal center'}  do |f|
  - if @account.errors.any?
    #error_explanation
      %h2
        = pluralize(@account.errors.count, "error")
        prohibited this account from being saved:
      %ul
        - @account.errors.full_messages.each do |message|
          %li= message

  %fieldset
  %legend= t('h1.account_details')

  .field
    = f.label :name, t('account.name')
    = f.text_field :name, size: 30
    %br/
  .field
    = f.label :age, t('account.age')
    = f.number_field :age, size: 30
  .actions
    = f.submit

app/views/accounts/edit.html.haml
.all_file

= render 'form'

= link_to 'Show', @account
|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
.all_file
%h1= t('h1.account_list')
%table
  %thead
    %tr
      %th= Account.human_attribute_name(:name)
      %th= Account.human_attribute_name(:age)
      %th{:colspan => "3"}
  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.name
        %td= account.age
        %td= link_to t('buttons.button_show'), account, class: 'btn btn-primary'
        %td= link_to t('buttons.button_edit'), edit_account_path(account), class: 'btn btn-warning'
        %td= link_to t('buttons.button_destroy'), account, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
%br/
.links
  = link_to t('links.link_new_account'), new_account_path, class: 'btn btn-info'
  %br/
  = link_to t('links.link_back_product_list'), products_path

app/views/accounts/new.html.haml
%h1= t('h1.new_account')
= render 'form'
= link_to t('buttons.button_back'), accounts_path

app/views/accounts/show.html.haml
.all_file
%p{:id => 'notice'}
  = notice

%p
  %strong Name:
  = @account.name
%p
  %strong Age:
  = @account.age
= link_to 'Edit', edit_account_path(@account)
= link_to 'Back', accounts_path

app/views/carts/confirm.html.haml
%h1= "Confirm you order"

= form_tag send_order_path do
  .form-group
    = label_tag :email, 'put your email'
    %br
    = text_field_tag :email
  .actions
    = submit_tag 'confirm order'

  = link_to 'Back to cart', cart_path, method: :get, class: 'btn btn-default btn-sm'

app/views/carts/order.html.haml
.all_file
  %h1= 'Your order'

  .order_text
    %p= 'Total price, UAH'
  .order_price
    = @total_sum

  = form_tag send_mail_path do
    .form-group
      = label_tag 'email', 'Email', class: 'col-md-4 control-label'
      .col-md-6
        = email_field_tag 'email', current_user.email, class: 'form-control'
    .submit_button
      = submit_tag 'Confirm order', class: 'btn btn-success'
  .order_button
    = button_to 'Back to cart', cart_path, method: :get, class: 'btn btn-primary'

app/views/carts/show.html.haml
.index_style
  .h1= t('h1.cart')
  %table.table.table-hover
    %thead
      %tr
        %th= t('product.name')
        %th= t('product.description')
        %th= t('product.price')
    %tbody
      - @products_in_cart.each do |product|
        %tr
          %td= product.name
          %td= product.description
          %td= product.price
  %br
  .links
    = link_to t('buttons.button_go_product_list'), products_path, class: 'btn btn-default'
    = link_to 'Order', order_cart_path, method: :get, class: 'btn btn-default'

app/views/friendships/_form.html.haml
= form_for(@friendship) do |f|
  - if @friendship.errors.any?
    #error_explanation
      %h2
        = pluralize(@friendship.errors.count, "error")
        prohibited this friendship from being saved:
      %ul
        - @friendship.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :account_id
    %br/
    = f.number_field :account_id
  .field
    = f.label :friend_id
    %br/
    = f.number_field :friend_id
  .field
    = f.label :create
    %br/
    = f.text_field :create
  .field
    = f.label :destroy
    %br/
    = f.text_field :destroy
  .actions
    = f.submit

app/views/friendships/edit.html.haml
%h1 Editing Friendship
= render 'form'
= link_to 'Show', @friendship
|
= link_to 'Back', friendships_path

app/views/friendships/index.html.haml
%p#notice= notice
%h1 Listing Friendships
%table
  %thead
    %tr
      %th Account
      %th Friend
      %th Create
      %th Destroy
      %th{:colspan => "3"}
  %tbody
    - @friendships.each do |friendship|
      %tr
        %td= friendship.account_id
        %td= friendship.friend_id
        %td= friendship.create
        %td= friendship.destroy
        %td= link_to 'Show', friendship
        %td= link_to 'Edit', edit_friendship_path(friendship)
        %td= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Friendship', new_friendship_path

app/views/friendships/new.html.haml
%h1 New Friendship
= render 'form'
= link_to 'Back', friendships_path

app/views/friendships/show.html.haml
%p#notice= notice
%p
  %strong Account:
  = @friendship.account_id
%p
  %strong Friend:
  = @friendship.friend_id
%p
  %strong Create:
  = @friendship.create
%p
  %strong Destroy:
  = @friendship.destroy
= link_to 'Edit', edit_friendship_path(@friendship)
|
= link_to 'Back', friendships_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rails_yZin_shop
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.body
    %header.header
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      .langs
        =link_to 'EN', '?locale=en', class: "btn btn-success"
        =link_to 'UA', '?locale=ua', class: "btn btn-warning"
        =link_to 'PL', '?locale=pl', class: "btn btn-danger"
      .logins
        - if user_signed_in?
          Signed in as #{current_user.email}. Not you?
          \#{link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'btn btn-warning'}
        - else
          = link_to "Sign up", new_user_registration_path, class: 'btn btn-info'
          or
          = link_to "sign in", new_user_session_path, class: 'btn btn-success'
      %br/
      .demo
        = link_to "Demo shop", root_url, class: "btn btn-info"
        = link_to 'Shopping cart', cart_path, class: 'btn btn-primary'
  %main.main
    = yield
  %footer.footer
    %span= 'All rights reserved'
    %span &copy; 2016

app/views/products/_empty.html.haml
%h2= 'Oooopsss the list is empty'
%h3= 'push on the pic to add some new product'

.links.empty_box_pic
  = link_to image_tag('empty_box.jpg', size: "90x60"), new_product_path

%br
= link_to 'Create new product', new_product_path, class: 'btn btn-default'
= link_to 'All accounts', accounts_path, class: 'btn btn-info'

app/views/products/_form.html.haml
.form
= form_for @product, :html => {:class => 'form-horizontal', multipart: true} do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited this product from being saved:

      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :name, t('product.name')
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :description, t('product.description')
    = f.text_field :description, class: 'form-control'
  .field
    = f.label :price, t('product.price')
    = f.number_field :price, class: 'form-control'
  .actions
    = f.submit

app/views/products/_list.html.haml
.all_file
  - flash.each do |key, value|
    .alert{role: "alert", class: colored_class(key)}= value
  .links.cart_pic
    = link_to image_tag('cart.gif', size: "90x60"), cart_path
%h2.header1= t('h1.product_list')

%table.table.table-condensed.my_table
  %thead
    %tr
      %th= 'Image'
      %th= t('product.name')
      %th= t('product.description')
      %th= t('product.price')
      %th(colspan="4")
  %tbody
    - @products.each do |product|
      %tr
        %td= image_tag product.image.url(:thumb)
        %td= product.name
        %td= product.description
        %td= product.price
        %td= link_to t('buttons.button_show'), product, class: 'btn btn-default btn-sm'
        %td= link_to t('buttons.button_edit'), edit_product_path(product), class: 'btn btn-default btn-sm'
        %td= link_to t('buttons.button_destroy'), product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm'
        %td= button_to t('buttons.button_add_cart'), add_to_cart_path(product_id: product.id), remote: true

.links
= link_to t('buttons.button_create_product'), new_product_path, class: 'btn btn-success'
= link_to t('buttons.button_all_accounts'), accounts_path, class: 'btn btn-info'

app/views/products/edit.html.haml
.index_style
  %h1 Edit

  = render 'form'

app/views/products/index.html.haml
.all_file
  = render product_list_partial_name

app/views/products/new.html.haml
.index_style
  %h1= t('h1.new_product')
  = render 'form'
  = link_to t('buttons.button_back'), products_path, class: 'btn btn-default btn-sm'

app/views/products/show.html.haml
.index_style
  .product_image
    = image_tag @product.image.url(:medium)
  %p.show_text
    %strong Name:
    = @product.name
  %p.show_text
    %strong Description:
    = @product.description
  %p.show_text
    %strong Price:
    = @product.price
  .links.links_inline
    = link_to t('buttons.button_edit'), edit_product_path(@product), class: 'btn btn-success'
    .links.links_inline
    = link_to t('buttons.button_destroy'), @product, method: :delete, data: { confirm: 'You sure?' }, class: 'btn btn-danger'
    .links.links_inline
    = link_to t('buttons.button_back'), products_path, class: 'btn btn-info'